name: main
on: push
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get install inkscape pandoc texlive-xetex
      - uses: actions/checkout@v4
      - run: pip install ipykernel nbconvert pint open-atmos-jupyter-utils scipy PyMPDATA
      - run: python -m nbconvert --to pdf --execute shallow_water_projekt.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: shallow_water_projekt.pdf
